### ISSUE TITLE
Building RPMs without dkms

### ISSUE THREAD

**Issue by bne86** [NVIDIA/gdrcopy#190]
Hi,

for us its very important that we are able to build the kernel modules without DKMS. DKMS is pulling in several dependencies we do not want to install on our HPC machine (9XX nodes, 4 A100 each, diskless) because it would use to much memory.

Actually, we do not build the kmods on the nodes, we have a build-system that create RPMs we at the end use on a repository to distribute it to our several systems.

With the latest gdrcopy 2.2 changes it looks like you started to only support DKMS.  Do you think its possible to support two specfiles, one with and one without DKMS? Otherwise we always have to reverse engineer your dkms specfiles.

best regards

**Comment by pakmarkthub** [comment]
Hi @bne86,

We plan to release pre-built RPM and DEB packages in the near future. The DKMS for RPM build script is in preparation for that release.

Since you have a use case for kmod, we will bring back the kmod build script. However, kmod will not be a part of those pre-built packages -- so you need to build it yourself using the provided script. Is this ok with you?

Sincerely yours

**Comment by bne86** [comment]
Definitely, thanks!

**Comment by pakmarkthub** [comment]
The PR has been merged. Closing this issue.
